title: Drake's 5e Homebrew
description: Work in Progress
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: Images/drakessw5elogo-2.png
aux_links:
search_enabled: true
search.rel_url: false